image: node:10.15.0

pipelines:
  default:
    - step:
        name: Playwright-Automation-Tests-Angular-App
        image: mcr.microsoft.com/playwright:v1.38.0-jammy
        script:
          - npm install
          - npx playwright install
          - npm run test