image: node:10.15.0

pipelines:
  default:
    - step:
        name: Playwright-Test-Automation
        image: mcr.microsoft.com/playwright:v1.38.0-jammy
        script:
          - npm install
          - npx playwright install chrome
          - npx playwright install msedge
          - npx playwright install
          - npm run test